# https://github.com/sxyazi/yazi/blob/5c88f268968005ae34be359d614bca024001ce3f/yazi-config/preset/yazi-default.toml
# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.

[mgr]
ratio          = [ 1, 4, 3 ]
sort_by        = "mtime"
sort_reverse   = true

[previewers]
previewers = [
    { mime = "video/*", run = "video", frame_offset = 1 },
]

[opener]
play = [
	{ run = "mpv %s1",    desc = "Play", for = "linux", orphan = true },
	{ run = "mediainfo %s1; echo 'Press enter to exit'; read _", block = true, desc = "Show media info", for = "unix" },
]
open = [
	{ run = "mpv %s1",    desc = "Open", for = "linux" },
]
