[config]
version_check = true

# [templates.m3colors]
# input_path = '~/.config/matugen/templates/quickkshell/colors.json'
# output_path = '~/.local/state/quickshell/user/generated/colors.json'
#
# [templates.wallpaper]
# input_path = '~/.config/matugen/templates/quickshell/wallpaper.txt'
# output_path = '~/.local/state/quickshell/user/generated/wallpaper/path.txt'
#
# [templates.kde_colors]
# input_path = '~/.config/matugen/templates/quickshell/kde-color.txt'
# output_path = '~/.local/state/quickshell/user/generated/color.txt'
#
# [templates.hyprland]
# input_path = '~/.config/matugen/templates/hypr/hyprland-colors.conf'
# output_path = '~/.config/hypr/hyprland-colors.conf'
#
# [templates.hyprlock]
# input_path = '~/.config/matugen/templates/hypr/hyprlock-colors.conf'
# output_path = '~/.config/hypr/hyprlock-colors.conf'

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel/theme.ini'
output_path = '~/.config/fuzzel/theme.ini'

# [templates.gtk3]
# input_path = '~/.config/matugen/templates/gtk-3.0/gtk.css'
# output_path = '~/.config/gtk-3.0/gtk.css'
#
# [templates.gtk4]
# input_path = '~/.config/matugen/templates/gtk-4.0/gtk.css'
# output_path = '~/.config/gtk-4.0/gtk.css'

