name: base
description: Module description

packages:
  core:
    - base
    - base-devel
    - linux
    - linux-firmware
    - efibootmgr
    - mesa
    - libva-mesa-driver

  intel:
    - intel-ucode

    - vulkan-intel
    - intel-media-driver
    - libva-intel-driver

    - intel-gpu-tools

    # - vlc-plugin-quicksync

  amd:
    - vulkan-radeon

    # - radeontop
    # - amdgpu_top

  system:
    - pipewire
    - pipewire-alsa
    - pipewire-pulse
    - wireplumber

    - openssh
    # - iwd
    - networkmanager

    - reflector

    - cpupower
    - thermald
    - irqbalance
    - auto-cpufreq

units:
  - NetworkManager.service
  - sshd.service
  - fstrim.timer
  - reflector.timer
  - cpupower.service
  - thermald.service
  - irqbalance.service
  - auto-cpufreq.service


# pre_install_hook:
# post_install_hook: scripts/my-setup.sh
# pacman -Ql openssh | grep systemd/system
