name: base
description: Module description

packages:
  core:
    - base
    - base-devel

    - linux
    - linux-headers
    - linux-zen
    - linux-zen-headers

    - linux-firmware
    - efibootmgr

  graphic:
    - mesa
    - mesa-utils
    - vulkan-mesa-implicit-layers
    - libva
    - libva-utils

  intel:
    - intel-ucode

    - vulkan-intel
    # - intel-media-driver
    - libva-intel-driver

    # - intel-gpu-tools

    # - vlc-plugin-quicksync

  amd:
    - vulkan-radeon

    # - radeontop
    # - amdgpu_top

  file:
    - ntfs-3g
    - udisk2
    - udiskie
    # - udisk2-btrfs
    # - btrfs-progs
    # - udisks2-lvm2
    # - lvm2
    # - gvfs

  sound:
    - pipewire
    - pipewire-alsa
    - pipewire-pulse
    - wireplumber

  network:
    # - ufw
    # - gufw
    - openssh
    # - iwd
    - networkmanager

  power:
    - preload
    # - cpupower
    - thermald
    - irqbalance
    - auto-cpufreq
    - ananicy-cpp

  other:
    - reflector

units:
  - NetworkManager.service
  - sshd.service
  - fstrim.timer
  - reflector.timer
  - cpupower.service
  - thermald.service
  - irqbalance.service
  - auto-cpufreq.service
  - preload.service
  - ananicy-cpp.service
  - udiskie.service (user)


# pre_install_hook:
# post_install_hook: scripts/my-setup.sh
# pacman -Ql openssh | grep systemd/system
