name: base
description: Module description

packages:
  core:
    - base
    - base-devel
    - linux
    - linux-firmware
    - efibootmgr

  intel:
    - intel-ucode

    - mesa
    # - lib32-mesa

    - vulkan-intel
    # - lib32-vulkan-intel

    - vulkan-radeon
    # - lib32-vulkan-radeon

    - xf86-video-amdgpu
    - xf86-video-ati
    - xf86-video-intel

    # - vpl-gpu-rt
    - libva-utils
    - libva-mesa-driver
    - intel-media-driver
    - linux-firmware-intel

  system:
    - pipewire
    - pipewire-alsa
    - pipewire-pulse
    - pipewire-jack
    - wireplumber

    - openssh
    - networkmanager # iwd

    - reflector

    - cpupower
    - thermald
    - irqbalance
    - auto-cpufreq

units:
  - NetworkManager.service
  - sshd.service
  - fstrim.timer
  - reflector.timer
  - cpupower.service
  - thermald.service
  - irqbalance.service
  - auto-cpufreq.service


pre_install_hook:
post_install_hook: scripts/my-setup.sh
# pacman -Ql openssh | grep systemd/system
