name: casual life application
description: desktop

packages:
  extra:
    - less
    - luarocks
  commandline:
    - fd
    - fzf
    - 7zip
    - bat
    - btop
    - nvtop
    - stow
    - fastfetch
    - rsync
    - yazi
    - tldr
    - sudo
    # - aria2
  gui:
    - helium-browser-bin (aur)
    - google-chrome (aur)
    - thorium-browser-bin (aur)
    - brave-bin (aur)
    - obsidian
    - telegram-desktop
    - vesktop-bin (aur)
