name: desktop environment
description: desktop

packages:
  core:
    - hyprland
    - uwsm
    - libnewt
    - app2unit
    - xdg-user-dirs
    - xdg-desktop-portal-gtk
    - xdg-desktop-portal-hyprland
    - sddm

    # - quickshell
    - hypridle
    - hyprlock
    - hyprpaper

    # - mako
    - swaync
    - hyprpolkitagent
    - hyprsunset
    - hyprlauncher
    - fuzzel
    - thunar
    # - superfile
    - wl-clipboard
    - cliphist
    # - copyq, wl-clip-persist, nwg-clipman

    # - sans-serif, FontAwesome
    - noto-fonts
    - noto-fonts-cjk
    - noto-fonts-emoji
    - ttf-fira-code
    - ttf-jetbrains-mono-nerd
    - tex-gyre-fonts
    # - ntfs-3g
    # - udiskie

    # - hyprcursor
    # - qt6-base, qt6-wayland, qt6ct, ,qt6-multimedia, qt6-multimedia-ffmpeg, hyprland-qt-support, hyprqt6engine
    # - aquamarine
    # - Nyxt, luakit

  utils:
    - foot
    - starship
    - firefox

    - fcitx5
    - fcitx5-unikey
    - fcitx5-configtool

    - mpv
    - vlc
    # - vlc-gui-qt
    # - vlc-plugins-base
    # - vlc-plugins-extra
    # - vlc-plugin-ffmpeg
    # - vlc-plugin-pulse
    # - vlc-plugin-gstreamer

    - imv
    - gthumb

    - tumbler
    # - ffmpegthumbnailer # libopenraw ueberzugpp
    # - speech-dispatcher speech-dispatcher-utils
    # - image/video deduplicate
    - batsignal
    - flameshot

# maybe enable all of them as system, they nesscessary , i mean
units:
  - sddm.service
  - batsignal.service (user)
  - hyprpolkitagent.service (user)
  - hyprsunset.service (user)
  - hypridle.service (user)
  - hyprpaper.service (user)
  # - mako.service (user)
  - swaync.service (user)
  - waybar.service (user)
  - foot-server.service (user)
  - xdg-user-dirs.service (user)
