name: dev
description: dev

packages:
  general:
    - git
    - tmux
    - visual-studio-code-bin (aur)
    - neovim
    # - podman
    # - podman-tui
    # - podman-desktop
  cpp:
    - cmake
    - ninja
    - ccache
    - conan-bin (aur)

    - clang
    # - lldb
    # - clangd
    - lld
    - mold

    - libc++
    - libc++abi

  misc:
    - go
  # - uv
  # - rustup

