packages:
  tmp:
    # - borg
    # - restic
    - timeshift

    # - task
    # - timew
    # - just
    # - envdir

    # - powertop
    # - direnv
    # - alsa-utils and audio stack with alsa
    # - tlp

    # - dust
    # - dua-cli
    # - progress

    # - gstreamer
    # - gst-plugins-good
    # - gst-plugins-base
    # - gst-plugins-bad
    # - gst-plugins-ugly
    # - gst-libav

    # - activitywatch-bin (aur)

    # sddm-astronaut-theme
    # - gum
    # - hunspell
    # - qt6-svg
    # - qt6-virtualkeyboard
    # - qt6-multimedia-ffmpeg

    - very
    - handsome (aur)
